Abstract token cache to interface to allow for custom implementations
microsoft/kiota-authentication-phpleague-php pull request #18
Opened 2023-02-24 14:10 UTC by Robertbaelde

Abstracts caching of tokens to allow for custom implementations (for example, storing tokens between requests).

The constructor of `PhpLeagueAccessTokenProvider` falls back to a default "inMemory" cache to enable backwards compatibility.

2023-02-24 14:11 UTC, Robertbaelde commented
@microsoft-github-policy-service agree

2023-03-16 09:29 UTC, Ndiritu approved these changes

2023-03-16 10:23 UTC, Robertbaelde commented
@Ndiritu Looks like the build for php 8.0 is failing due to some randomness, or something out for this PR? (Sonorcloud config  thing?). Who would be the right person to look into that?

2023-03-16 13:13 UTC, baywet requested changes
@Robertbaelde Thanks for the contribution. I do have a concern.
As per the validation, pull requests from forks don't have access to secrets for obvious security reasons, and we use one for sonarcloud, which is what's failing in your case.
@Ndiritu can you create an issue to add a condition so we don't execute the sonarcloud step when the secret is not present please?

2023-03-16 13:13 UTC, baywet commented on src/Cache/InMemoryAccessTokenCache.php
> +    public function getAccessToken(): ?AccessToken
@Ndiritu I don't know enough about PHP lifecycle, especially when using things like dependency injection.
But this doesn't look thread safe in scenarios like on behalf:
1. multiple requests come from the front end for different users in browser.
2. the token trade is being made to get a on behalf token for the first user that comes in.
3. second user gets the token from the first one.
4. we now have identities swap, a major security concern.

Of course that only holds true if the authentication provider is persisted in memory across requests incoming to the service. But I'd like this scenario to be doubled check before we merge this.

2023-03-16 13:22 UTC, Robertbaelde commented on src/Cache/InMemoryAccessTokenCache.php
> +    public function getAccessToken(): ?AccessToken
@baywet By nature php has a single lifecycle per request. There are some servers/frameworks, that enable multi-threading. ([Swoole](https://openswoole.com/), [Roadrunner](https://roadrunner.dev/)). 

In that case, it depends on the service container used, but potentially it might be harmful. So lets fix the issue. 

Is my assumption correct, that if we scope the access token to the `TenantId` from the `TokenRequestContext` we would mitigate this issue?

2023-03-16 14:51 UTC, baywet commented on src/Cache/InMemoryAccessTokenCache.php
> +    public function getAccessToken(): ?AccessToken
we'd also need to include the user id in case it's not an application only context. And the way's you can obtain that to compare with the token in cache vary depending on the authentication flow.

2023-03-16 15:19 UTC, Robertbaelde commented on src/Cache/InMemoryAccessTokenCache.php
> +    public function getAccessToken(): ?AccessToken
I've added `getIdentity()` to the `TokenRequestContext` interface, so each authentication context can provide its own identity key based on what makes sense for that context. This would be a breaking change though. 

Please let me know if this is the wrong direction, different (Microsoft) authentication contexts aren't my speciality.

2023-03-16 15:21 UTC, baywet commented on src/Cache/InMemoryAccessTokenCache.php
> +    public function getAccessToken(): ?AccessToken
Thanks for making that change. @Ndiritu can you review those cache keys for each context please? My guess is we need something like tenantid-clientid for app only and something like tenantid-clientid-userid for delegated.

2023-03-20 14:41 UTC, Ndiritu commented on src/Cache/InMemoryAccessTokenCache.php
> +    public function getAccessToken(): ?AccessToken
Sorry for the delay.

@baywet, I agree with the suggested cache keys.

2023-03-20 14:45 UTC, baywet commented on src/Oauth/BaseSecretContext.php
> +        return $this->getTenantId();
yeah it'd make sense to have caching "not do anything" when it doesn't get a cache key. And to avoid provided default blanket keys through the inheritance so we don't end up crossing wires in the future.

2023-03-20 15:01 UTC, Ndiritu commented on src/Cache/InMemoryAccessTokenCache.php
> +    public function getAccessToken(): ?AccessToken
Sure. @Robertbaelde can we merge to a feature branch for now? I can then define the identities for the different token request contexts and you can take a look when we PR into `dev`?

2023-04-20 11:33 UTC, merged